apiVersion: v1
kind: Pod
metadata:
  name: net-debug
  namespace: default
  labels:
    app: net-debug
spec:
  restartPolicy: Never
  containers:
    - name: net-debug
      image: ghcr.io/theLemonday/netshoot
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
